### ISSUE TITLE
warnings being raised

### ISSUE THREAD

**Issue by jGaboardi** [martinfleis/sdss22-workshop#8]
The following are the current warnings being raised as of [2bceb56](https://github.com/martinfleis/sdss22-workshop/pull/6/commits/2bceb56272b4ea086698879cdf4746988f1102de):

* [x] Cell 15 – `pandas` `FutureWarning` – *resolved in pysal/momepy#384*
```python
streets = momepy.remove_false_nodes(streets)
streets = streets[["geometry"]]
streets["nID"] = range(len(streets))
#/momepy/preprocessing.py:273: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```
* [x] Cell 16 – `momepy` `UserWarning` – *probably best to leave as for demo purposes and not suppress*
```python
limit = momepy.buffered_limit(buildings, 100)
tessellation = momepy.Tessellation(buildings, "uID", limit, verbose=False, segment=1)
tessellation = tessellation.tessellation
#momepy/elements.py:395: UserWarning: Tessellation contains MultiPolygon elements. Initial objects should be edited. unique_id of affected elements: [8364, 9374, 8366, 5110, 2018]
```
* [x] Cell 25 – `matplotlib_inline`  `DeprecationWarning` – *should suppress in notebook*
```python
fig, ax = plt.subplots(1, 2, figsize=(24, 12))
buildings.plot("eri", ax=ax[0], scheme="natural_breaks", legend=True)
buildings.plot("elongation", ax=ax[1], scheme="natural_breaks", legend=True)
ax[0].set_axis_off()
ax[1].set_axis_off()
#matplotlib_inline/config.py:68: DeprecationWarning: InlineBackend._figure_format_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
```
* [x] Cell 34 (1) – `numpy`  `RuntimeWarning` – *probably should suppress in code base.* @martinfleis thoughts? — resolved by https://github.com/pysal/momepy/pull/389
```python
profile = momepy.StreetProfile(streets, buildings)
#numpy/lib/nanfunctions.py:1878: RuntimeWarning: Degrees of freedom <= 0 for slice.
```
* [x] Cell 34 (2) – `numpy`  `RuntimeWarning` – *probably should suppress in code base.* @martinfleis thoughts? — resolved by https://github.com/pysal/momepy/pull/389
```python
profile = momepy.StreetProfile(streets, buildings)
#momepy/dimension.py:640: RuntimeWarning: invalid value encountered in long_scalars
```
* [x] Cell 48 (1) – `momepy`/`numpy`  `DeprecationWarning` – *probably should solve in code base, but **must** suppress in notebook if not solved. This is thrown ***a ton*** of times and seems to be (at least partially responsible for) #3 — resolved via pysal/momepy#387*
```python
percentiles = []
for column in merged.columns.drop(
    ["uID", "nodeID", "nID", "mm_len", "node_start", "node_end", "geometry"]
):
    perc = momepy.Percentiles(merged, column, queen_3, "uID", verbose=False).frame
    perc.columns = [f"{column}_" + str(x) for x in perc.columns]
    percentiles.append(perc)
#momepy/diversity.py:907: DeprecationWarning: the `interpolation=` argument to nanpercentile was renamed to `method=`, which has additional options.
#Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
```
* [x] Cell 48 (2) – `momepy`/`numpy`  `RuntimeWarning` – *probably should solve in code base, but **should at least** suppress in notebook if not solved. This is thrown ***a handful*** of times.* @martinfleis thoughts?  — *resolving via pysal/momepy#395*
```python
percentiles = []
for column in merged.columns.drop(
    ["uID", "nodeID", "nID", "mm_len", "node_start", "node_end", "geometry"]
):
    perc = momepy.Percentiles(merged, column, queen_3, "uID", verbose=False).frame
    perc.columns = [f"{column}_" + str(x) for x in perc.columns]
    percentiles.append(perc)
#numpy/lib/nanfunctions.py:1559: RuntimeWarning: All-NaN slice encountered
```
* [x] Cell 53 – `bokeh`  `DeprecationWarning` – *should suppress in notebook*
```python
show(cgram.bokeh())
#bokeh/io/notebook.py:487: DeprecationWarning: The `source` parameter emit a  deprecation warning since IPython 8.0, it had no effects for a long time and will  be removed in future versions.
```

xref #6

**Comment by martinfleis** [comment]
- Cell 16 is expected, I'd keep that.
- Cell 25 is not fixable by us even if we wanted, right?
- Cell 34 (1) is probably something we should fix on our side, yes.
- Cell 34 (2) the same, should be fixed.
- Cell 48 (2) that is also something we could catch in momepy.
- Cell 53 - if we get rid of clustergram, this will go with it.

**Comment by jGaboardi** [comment]
>- Cell 25 is not fixable by us even if we wanted, right?

Correct

>- Cell 34 (1) is probably something we should fix on our side, yes.
>- Cell 34 (2) the same, should be fixed.
>- Cell 48 (2) that is also something we could catch in momepy.

OK, I'll look into these.

>- Cell 53 - if we get rid of clustergram, this will go with it.

`clustergram` is growing on me. I think I'd like to see it kept in the tutorial unless you feel super strongly about removing it? Without it, we can't do the cool building cluster plot in cell 57.

**Comment by martinfleis** [comment]
ffs, the env now resolves with pandas 1.5 and matplotlib 3.6 that come with additional warnings... I suggest we pin the environment.

**Comment by jGaboardi** [comment]
It never stops. LOL
